'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'suanming-age-'));
test.after(()=>{assert.ok(temporary.startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(temporary,{recursive:true,force:true});});
const {build,validateArtifact}=require('../scripts/relationship.cjs');const {predictAge}=require('../scripts/relationship-age.cjs');const {digest}=require('../scripts/common.cjs');const {main}=require('../scripts/run.cjs');
const person=(id,date='2005-12-23',time='08:37',timezone='Asia/Shanghai')=>({id,birth:{calendar:'solar',date,time,timezone,gender:'male'}});
const input=()=>({mode:'relationship',chart_mode:'bazi',question:'合成年上年下与亲密主题',people:[person('a')],context:{topics:['age_relation','sexual_ability','partner_image']},options:{partner_star_model:'wealth'}});
const resign=d=>{delete d.checksum;d.checksum={algorithm:'sha256-canonical-json',value:digest(d)};};
test('八字柱位保留旁证，但不再把六亲位置当实际年龄公式',()=>{const d=build(input()),a=d.age_relation.predictions[0];assert.equal(a.tendency,'none');assert.equal(a.status,'insufficient_evidence');assert.equal(a.input_scope,'single_natal_chart');assert.equal(a.exact_age_gap,null);assert.equal(a.models[0].position_tendency,'older');assert.equal(a.models[0].use,'auxiliary_only');assert.deepEqual(a.models[0].position_weights,{older:1,peer:0,younger:0.3});assert.ok(a.cues.some(x=>x.source.source_id==='BZ-YEAR-S'));validateArtifact(d);});
test('财官模型各留柱位旁证，all 分歧不能投票产生最终年龄方向',()=>{const i=input();i.options.partner_star_model='authority';const a=build(i).age_relation.predictions[0];assert.equal(a.tendency,'none');assert.equal(a.models[0].position_tendency,'peer');assert.equal(a.models[0].position_weights.peer,0.6);i.options.partner_star_model='all';const b=build(i).age_relation.predictions[0];assert.equal(b.tendency,'none');assert.deepEqual(b.models.map(m=>m.position_tendency),['older','peer']);assert.equal(b.auxiliary_model_agreement,false);});
test('另一人出生年份大幅改变不影响本人的年龄预测',()=>{const i=input(),a=build(i).age_relation.predictions[0];i.people.push(person('b','1901-01-01','12:00'));assert.deepEqual(build(i).age_relation.predictions[0],a);i.people[1]=person('b','2090-01-01','12:00');assert.deepEqual(build(i).age_relation.predictions[0],a);});
test('仅时柱和相等柱位线索仍只是辅助，配偶星缺位不补造',()=>{const mock=items=>({bazi:{calculations:{score_ledger:items}}});const item=(id,source,weight)=>({id,source,weight,ten_god:'正财',stem:'甲',kind:'visible_stem'});const a=predictAge(mock([item('H','BZ-HOUR',1)]),'a','wealth');assert.equal(a.tendency,'none');assert.equal(a.models[0].position_tendency,'younger');const b=predictAge(mock([item('Y','BZ-YEAR',1),item('H','BZ-HOUR',1)]),'a','wealth');assert.equal(b.tendency,'none');assert.equal(b.models[0].position_tendency,'mixed');assert.equal(predictAge(mock([]),'a','wealth').models[0].position_tendency,'none');});
test('仅紫微已可执行年龄模块，不再要求本人八字',()=>{const i=input();i.chart_mode='ziwei';const d=build(i),a=d.age_relation.predictions[0];assert.notEqual(a.status,'bazi_required');assert.deepEqual(a.models,[]);assert.ok(a.ziwei.spouse_palace.id);assert.equal(d.intimacy_features[0].physiological_ability,null);assert.equal(d.partner_images.length,1);validateArtifact(d);});
test('年龄推演与对象画像都加入重算校验，不用用户自述覆盖盘面',()=>{for(const mutate of [d=>d.age_relation.predictions[0].tendency='younger',d=>d.partner_images[0].dimensions.appearance[0].tag='伪造画像']){const d=build(input());mutate(d);resign(d);assert.throws(()=>validateArtifact(d),/当前程序重算/);}const i=input(),a=build(i);i.context.narrative='我偏爱年下';assert.deepEqual(build(i).age_relation,a.age_relation);});
function capture(fn){const saved=console.log,result=[];console.log=x=>result.push(JSON.parse(x));try{fn();return result;}finally{console.log=saved;}}
test('四种模式默认仅生成计算 JSON；显式报告可从校验数据导出而不改 JSON',()=>{const dir=fs.mkdtempSync(path.join(temporary,'age-output-'));const fixtures=[require('../examples/input.json'),require('../examples/liuyao-input.json'),require('../examples/relationship-single-input.json'),input()];fixtures.forEach((i,n)=>{const f=path.join(dir,`input-${n}.json`),out=path.join(dir,`result-${n}`);fs.writeFileSync(f,JSON.stringify(i));const result=capture(()=>main(['--input',f,'--out',out]))[0];assert.equal(result.report_generated,false);assert.deepEqual(fs.readdirSync(out),['chart.json']);assert.equal(fs.existsSync(path.join(out,'reading.md')),false);const chart=path.join(out,'chart.json'),bytes=fs.readFileSync(chart);const report=capture(()=>main(['--render',chart,'--out',out]))[0];assert.equal(report.report_generated,true);assert.equal(report.recalculated,true);assert.equal(fs.existsSync(path.join(out,'report.html')),true);assert.deepEqual(bytes,fs.readFileSync(chart));});});
test('明确请求可同时排盘及生成报告；篡改数据导出失败且不产生报告',()=>{const dir=fs.mkdtempSync(path.join(temporary,'age-report-')),f=path.join(dir,'input.json'),out=path.join(dir,'requested');fs.writeFileSync(f,JSON.stringify(input()));const r=capture(()=>main(['--input',f,'--out',out,'--report']))[0];assert.equal(r.report_generated,true);assert.equal(r.files.length,3);const chart=path.join(out,'chart.json'),d=JSON.parse(fs.readFileSync(chart));d.age_relation.predictions[0].tendency='younger';fs.writeFileSync(chart,JSON.stringify(d));const bad=path.join(dir,'rejected');assert.throws(()=>main(['--render',chart,'--out',bad]));assert.equal(fs.existsSync(bad),false);});
