'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const md=s=>esc(s).replace(/[\\`*_\[\]{}()!|]/g,'\\$&').replace(/\r?\n/g,' ');
function makeReport(d){
 const {chart:c,calculations:r}=d;const sections=[];
 const section=(title,headers,rows,note='')=>sections.push({title,headers,rows,note});
 section('占问与起卦口径',['项目','结果'],[['问题',d.input.question],['占时',`${d.input.time.date} ${d.input.time.time} ${d.input.time.timezone}`],['实际时区偏移',d.normalized.utc_offset],['UTC 瞬间',d.normalized.utc_instant],['摇卦来源',d.input.casting.coins?'六次三枚铜钱，正面=3 / 反面=2':'用户提供六次爻值 6/7/8/9'],['顺序','原始数组：初爻→上爻；下表：上爻→初爻'],['换日',d.input.options.day_boundary]]);
 section('本卦与变卦',['项目','本卦','变卦'],[['卦名',c.base.name,c.changed.name],['下卦 / 上卦',`${c.base.lower.name} / ${c.base.upper.name}`,`${c.changed.lower.name} / ${c.changed.upper.name}`],['卦宫',`${c.base.palace.trigram}宫（${c.base.palace.element}）`,`${c.changed.palace.trigram}宫（${c.changed.palace.element}）`],['八宫阶段',c.base.palace.stage,c.changed.palace.stage],['自身世 / 应',`${c.base.palace.shi_line} / ${c.base.palace.ying_line}`,`${c.changed.palace.shi_line} / ${c.changed.palace.ying_line}`],['动爻',r.moving_lines.join('、')||'无','只翻转 6 / 9 对应爻位'],['证据',c.base.id,c.changed.id]],'变爻六亲按本卦宫五行计算；变卦自身的世应为另外一组结构，不替代本卦世应。');
 section('历法上下文',['项目','结果'],[['年 / 月 / 日 / 时',`${c.calendar.year_ganzhi} / ${c.calendar.month_ganzhi} / ${c.calendar.day_ganzhi} / ${c.calendar.hour_ganzhi}`],['月建',c.calendar.month_branch],['日辰',c.calendar.day_branch],['日旬空',c.calendar.void_branches.join('、')],['口径',c.calendar.year_month_basis],['证据',c.calendar.id]]);
 section('六爻装卦表（自上而下）',['爻位','爻值 / 铜钱','本卦','纳甲 / 五行','六亲','六神','世应','动变（纳甲 / 六亲）','依据'],[...c.lines].reverse().map(l=>[l.position,`${l.value}${l.coins?` = ${l.coins.join('+')}`:''}`,l.symbol,`${l.najia} / ${l.element}`,l.relative,l.spirit,l.shi?'世':l.ying?'应':'',l.moving?`${l.yang?'阳→阴':'阴→阳'}；${l.changed.najia} / ${l.changed.relative_to_base_palace}`:'静',l.id]));
 section('逐爻机械关系',['爻位','旬空','月破','日冲','月建→爻','日辰→爻','变爻→本爻','化进 / 化退','依据'],r.line_ledger.map(x=>[x.line_id,x.void?'命中':'',x.month_break?'命中':'',x.day_clash?'命中':'',`${x.month_to_line.element_relation}${x.month_to_line.combine?'；六合':''}`,`${x.day_to_line.element_relation}${x.day_to_line.combine?'；六合':''}`,x.return_relation||'',x.advance?'进神配对':x.retreat?'退神配对':'',x.id]),'“生 / 克 / 受生 / 受克”表示箭头左侧五行相对于爻的关系。');
 section('缺失六亲与伏神候选',['所伏位置','纳甲','五行','六亲','依据'],r.hidden_relatives.map(h=>[h.position,h.najia,h.element,h.relative,h.id]),'某类六亲未在本卦出现时，从本宫纯卦对应爻位补出伏神候选。');
 section('计算校验',['项目','说明'],[['规则',r.rule_version],['表来源',`${d.provenance.rules_source.repository}@${d.provenance.rules_source.commit}`],['SHA-256',d.checksum.value]]);
 let markdown=`# ${md(d.input.label)} · 六爻计算报告\n\n本卦、变卦、装卦与逐爻关系计算。\n\n`;
 for(const s of sections){markdown+=`## ${s.title}\n\n| ${s.headers.map(md).join(' | ')} |\n| ${s.headers.map(()=>'---').join(' | ')} |\n`;
  markdown+=(s.rows.length?s.rows:[s.headers.map((_,i)=>i===0?'无':'')]).map(row=>`| ${row.map(md).join(' | ')} |`).join('\n')+'\n\n'+(s.note?s.note+'\n\n':'');}
 const tables=sections.map(s=>`<section><h2>${esc(s.title)}</h2><div class="scroll"><table><thead><tr>${s.headers.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${(s.rows.length?s.rows:[s.headers.map((_,i)=>i===0?'无':'')]).map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${s.note?`<p>${esc(s.note)}</p>`:''}</section>`).join('');
 const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.input.label)} · 六爻报告</title><style>body{margin:0;background:#f4f0e7;color:#273438;font:16px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:24px 12px}section{margin:18px 0;padding:18px;background:#fffdf8;border:1px solid #ddd6ca;border-radius:10px}h1{font-size:26px}h2{font-size:20px;color:#704034}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #ddd;min-width:55px;overflow-wrap:anywhere}th{background:#eee9dd}p{color:#586364}@media print{body{background:white}section{break-inside:avoid}.scroll{overflow:visible}}</style></head><body><main><h1>${esc(d.input.label)} · 六爻计算报告</h1><p>用户摇卦 → 程序装卦与计算 → 重算校验 → 依据结果解释</p>${tables}</main></body></html>`;
 return {markdown,html};
}
module.exports={makeReport};
