'use strict';
const {relationText}=require('./bazi-period-relations.cjs');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cell=s=>String(s??'—').replace(/\|/g,'\\|').replace(/[\r\n]/g,' ');
const source=s=>`${s.person_id}:${s.source_id??s.source_field}`;
function makeReport(data){
 const lines=['# 婚恋关系报告','',`问题：${cell(data.input.question)}`,''];
 for(const p of data.people){const c=p.chart,profile=data.profiles.find(x=>x.person_id===p.id),age=data.age_relation.predictions.find(x=>x.person_id===p.id),image=data.partner_images.find(x=>x.person_id===p.id);
  lines.push(`## ${cell(p.label)}（${p.id}）`,'',`出生：${c.normalized.solar_date} ${c.input.birth.time}；时区 ${c.input.birth.timezone}`,'');
  if(c.bazi){lines.push(`四柱：${c.bazi.chart.pillars.map(p=>p.ganzhi).join(' / ')}`,'',`八字日时口径：${c.input.options.time_basis}；时干：${c.input.options.bazi_hour_stem_rule}`,'');const t=c.bazi.chart.time_validation;if(t)lines.push(`真太阳时：${t.apparent_solar_datetime}；经度 ${t.longitude_degrees_east}；均时差 ${t.equation_of_time_minutes.toFixed(6)} 分；总修正 ${t.total_correction_minutes.toFixed(6)} 分。钟表日时 ${t.civil_day_hour.day}/${t.civil_day_hour.hour}，太阳日时 ${t.true_solar_day_hour.day}/${t.true_solar_day_hour.hour}；本次采用 ${t.selected_basis}。`,'');if(c.bazi.chart.jieqi_boundary_review.within_review_band)lines.push(`出生处于 ${c.bazi.chart.jieqi_boundary_review.name} 的 60 秒复核带；需要对照节气边界两侧候选。`,'');}
  if(data.input.context.topics.includes('age_relation')){lines.push('### 对象年龄倾向','',`${age.label} [${age.id}]`,'');for(const cue of [...age.ziwei.matches,...age.ziwei.opposite_support])lines.push(`${cue.use==='spouse_main'?'夫妻宫主规则':'辅助旁证'}：${cue.stars.join('、')}，${cue.direction} [${source(cue.source)}; ${cue.rule_id}]；《${cue.reference.book}》${cue.reference.chapter}·${cue.reference.locator}：“${cue.reference.original_excerpt}”。${cue.reference.url}`,'');for(const m of age.models)lines.push(`${m.model==='wealth'?'财星':'官杀'}柱位辅助：${m.label}；${m.ledger.map(x=>`${x.pillar_id} ${x.ten_god} [${source(x.source)}]`).join('；')||'未见所选候选星'}`,'');}
  if(image){lines.push('### 对象形象','');for(const [dim,label] of [['appearance','外形印象'],['temperament','气质'],['style','风格']]){const items=image.dimensions[dim].slice(0,4);if(items.length)lines.push(`${label}：${items.map(t=>`${t.tag} [${t.evidence_ids.join(', ')}]`).join('；')}`,'');}
   lines.push(`生肖缘分：${image.zodiac.affinity_candidates.map(x=>`${x.animal}（${x.relation}）`).join('、')} [${image.zodiac.id}]`,'');if(image.zodiac.boundary_difference)lines.push(`本次按八字立春口径取${image.zodiac.animal}，农历年生肖为${image.zodiac.lunar_new_year_animal}。`,'');
   lines.push('取象依据：','');for(const x of image.ledger)lines.push(`- ${x.detail} [${x.id}; ${source(x.source)}]`);lines.push('');}
  if(profile.bazi?.dayun.length){lines.push('### 大运与夫妻宫','','| 公历年标签 | 干支 | 显干 / 藏干十神 | 夫妻宫地支关系 | 四柱干支关系 | 依据 |','|---|---|---|---|---|---|');for(const y of profile.bazi.dayun)lines.push(`| ${y.start_year}–${y.end_year} | ${y.ganzhi} | ${cell(y.stem_ten_god+' / '+y.hidden_stems.map((s,i)=>s+'('+y.hidden_ten_gods[i]+')').join('、'))} | ${cell(relationText(y.day_branch_relations,'大运'))} | ${cell(relationText(y.pillar_relations,'大运'))} | ${source(y.source)} |`);lines.push('');}
  if(profile.bazi?.annual.length){lines.push('### 逐年流年与夫妻宫','','| 立春周期 | 干支 | 显干 / 藏干十神 | 夫妻宫地支关系 | 四柱干支关系 | 依据 |','|---|---|---|---|---|---|');for(const y of profile.bazi.annual)lines.push(`| ${y.lichun_cycle_year} | ${y.ganzhi} | ${cell(y.stem_ten_god+' / '+y.hidden_stems.map((s,i)=>s+'('+y.hidden_ten_gods[i]+')').join('、'))} | ${cell(relationText(y.day_branch_relations))} | ${cell(relationText(y.pillar_relations))} | ${source(y.source)} |`);lines.push('');}
  if(profile.ziwei){lines.push('### 紫微关注宫位','','| 宫位 | 主星 | 依据 |','|---|---|---|');for(const palace of profile.ziwei.focus_palaces)lines.push(`| ${palace.name} | ${palace.majorStars.map(s=>s.name).join('、')||'空主星宫'} | ${source(palace.source)} |`);lines.push('','### 紫微关注宫位的宫干四化','','| 发出宫 | 四化星 | 落入宫 | 自化 | 依据 |','|---|---|---|---|---|');for(const e of profile.ziwei.palace_stem_flying)lines.push(`| ${e.origin_palace} | ${e.star}化${e.mutagen} | ${e.target_palace} | ${e.is_self_transform?'是':'否'} | ${source(e.source)} |`);lines.push('');}
 }
 if(data.comparison){lines.push('## 双方结构对照','');const b=data.comparison.bazi;if(b){const d=b.day_master_projection;lines.push(`A 看 B：${d.a_to_b.ten_god}；B 看 A：${d.b_to_a.ten_god} [${d.id}]`,'','| A 柱 | B 柱 | 关系 | 依据 |','|---|---|---|---|');for(const p of b.pillar_matrix)lines.push(`| ${p.a_ganzhi} | ${p.b_ganzhi} | ${p.relations.map(r=>r.type).join('、')||'无规则命中'} | ${p.id} |`);lines.push('');}}
 if(data.input.context.topics.includes('sexual_ability')){lines.push('## 亲密互动与节奏','');for(const x of data.intimacy_features){lines.push(`人物 ${x.person_id} [${x.id}]`,'');if(x.bazi)lines.push(`十神线索：${x.bazi.ten_god_occurrences.map(t=>`${t.ten_god} [${source(t.source)}]`).join('；')}`,'');if(x.ziwei)lines.push(`宫位线索：${x.ziwei.palaces.map(p=>`${p.name} [${source(p.source)}]`).join('；')}`,'');}}
 if(data.context.narrative)lines.push('## 相处背景','',cell(data.context.narrative),'');
 lines.push(`规则：${data.provenance.rule_version} / ${data.provenance.image_rule_version}`,`校验和：${data.checksum.value}`,'');
 const markdown=lines.join('\n'),html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>婚恋关系报告</title><style>body{font:16px/1.7 system-ui;margin:0;background:#f7f5f1;color:#242424}main{max-width:1000px;margin:auto;padding:20px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}</style><main><pre>${esc(markdown)}</pre></main></html>`;
 return {markdown,html};
}
module.exports={makeReport};
